### ISSUE TITLE
Random crash on all devices : "Unmarshalling unknown type code xxx at offset xxx"

### ISSUE THREAD

**Issue by outadoc** [outadoc/lastfm-android#5]
Here are some stack traces

```
java.lang.RuntimeException: Unable to start service fm.last.android.scrobbler.ScrobblerService@ed9cc37 with Intent { act=com.android.music.queuechanged cmp=fr.outadev.lastfm.scrobb/fm.last.android.scrobbler.ScrobblerService (has extras) }: java.lang.RuntimeException: Parcel android.os.Parcel@c9ab536: Unmarshalling unknown type code 3014765 at offset 364
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3230)
    at android.app.ActivityThread.access$2200(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1506)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5821)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@c9ab536: Unmarshalling unknown type code 3014765 at offset 364
    at android.os.Parcel.readValue(Parcel.java:2349)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2623)
    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
    at android.os.BaseBundle.getInt(BaseBundle.java:795)
    at android.content.Intent.getIntExtra(Intent.java:5287)
    at fm.last.android.scrobbler.ScrobblerService.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3191)
    ... 8 more
```

```
java.lang.RuntimeException: Unable to start service fm.last.android.scrobbler.ScrobblerService@272aa2db with Intent { act=com.android.music.queuechanged cmp=fr.outadev.lastfm.scrobb/fm.last.android.scrobbler.ScrobblerService (has extras) }: java.lang.RuntimeException: Parcel android.os.Parcel@1e0befea: Unmarshalling unknown type code 3014765 at offset 364
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3007)
    at android.app.ActivityThread.access$2100(ActivityThread.java:162)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5421)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@1e0befea: Unmarshalling unknown type code 3014765 at offset 364
    at android.os.Parcel.readValue(Parcel.java:2228)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
    at android.os.BaseBundle.getInt(BaseBundle.java:794)
    at android.content.Intent.getIntExtra(Intent.java:4996)
    at fm.last.android.scrobbler.ScrobblerService.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
    ... 9 more
```

**Comment by outadoc** [comment]
Judging from the comments, it seems to be crashing when starting Google Play Music.

**Comment by cooperaj** [comment]
I'm 100% aware of how the work on OSS projects work, having a few myself, but having no Android dev. experience and a desire to Scrobble my Play music tracks I'd love to have this working. The alternatives are just rubbish and this seems the nicest app going (RIP WAIL).
